<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>mysql_runner.tests</RootNamespace>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="NExpect" Version="2.0.125" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="PeanutButter.FileSystem" Version="3.0.418" />
    <PackageReference Include="PeanutButter.RandomGenerators" Version="3.0.418" />
    <PackageReference Include="PeanutButter.TempDb.MySql.Connector" Version="3.0.418" />
    <PackageReference Include="PeanutButter.Utils" Version="3.0.418" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\mysql-runner\mysql-runner.csproj" />
  </ItemGroup>

</Project>
